version: '3.1'

services:

  redmine:
    image: redmine-dev
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    links:
      - db:db